name: worflow action Checks

on:
  [push]

jobs:
  testing-code:
    name: Testing source code
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout branch
        uses: actions/checkout@v2
      - 
        name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==6.2.5
          pip install pytest-mock==3.6.1
          pip install SQLAlchemy==1.3.24
          pip install pandas==1.1.5 
          pip install requests==2.26.0
          pip install pylint
          pip install black==21.11b1
          pip install yfinance
      -
        name: Run pylint
        run: |
          find . -name '*.py' -exec pylint {} \;
      -
        name: Run Black
        run: black .
      -
        name: Run unit tests
        run: python -m pytest -v